name: Generate JSON SBOM

on:
  push:
    branches: ["master"]


jobs:
  generate-sbom:
    runs-on: ubuntu-latest
    uses: CycloneDX/gh-dotnet-generate-sbom@master
    with:
      path: ./
      json: true
      github-bearer-token: ${{ secrets.GITHUB_TOKEN }}
